### ISSUE TITLE
Mermaid diagram not rendering

### ISSUE THREAD

**Issue by rice2000** [stellar/new-docs#121]
### What version are you using?
Google Chrome Version 81.0.4044.113

### What did you do?
Went to this page: 
https://developers.stellar.org/docs/enabling-deposit-and-withdrawal/setting-up-test-server/

### What did you expect to see?
A sequence diagram.

### What did you see instead?
Code for generating a sequence diagram.

**Comment by jeesunikim** [comment]
Needs ```mermaid wrapper. Closing it.
