### ISSUE TITLE
Right side navigation stops working once a user clicks H2 linked icon

### ISSUE THREAD

**Issue by jeesunikim** [stellar/new-docs#170]
![bug-right-side-nav-linked-header](https://user-images.githubusercontent.com/3912060/85419917-9b85e800-b540-11ea-9c02-81f0f9ec4354.gif)

### What did you do?
Go to [/docs](https://developers.stellar.org/docs/) that has the right side navigation and scroll down the page.

### What did you expect to see?
The right side navigation to highlight correctly as I scroll down each section on the page after clicking the clip icon that I see when hovering `H2` tags.

### What did you see instead?
The right side navigation stopped highlighting the section that is visible on the page after clicking the clip icon.

**Comment by jeesunikim** [comment]
[Comment](https://github.com/stellar/new-docs/pull/175#issuecomment-651290390) regarding to this to keep track of it

**Comment by shanzzam** [comment]
This is still an issue so am adding it to the Nebula team backlog as it's a technical issue.
