### ISSUE TITLE
Add new protocol 13 operations to "List of operations"

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/new-docs#177]
Protocol 13 added Fee Bump and modified Allow Trust. Allow Trust has been updated on the list of operations, but Fee Bump is missing here: https://developers.stellar.org/docs/start/list-of-operations/

I see we have a fee bump page [here](https://developers.stellar.org/docs/glossary/fee-bumps/) already which has result codes and describes the parameters in words.

**Comment by ire-and-curses** [comment]
I guess maybe there's nothing to add here. Now that I think about it, fee bump is not actually an operation. I raised this issue because I've always thought of this list as the full list of what is possible in Stellar, and it's missing fee bump. But since fee bump is a different type of transaction, I guess it doesn't make sense here. Maybe it would be enough to just link to the fee bump page from here though? "If you're looking for fee bump, see here" or something.

**Comment by rice2000** [comment]
Added a description for fee bumps here: https://developers.stellar.org/docs/glossary/fee-bumps/

But closing this since, as pointed out, fee bump isn't an operation, and so doesn't belong on the list of operations.
