### ISSUE TITLE
Disabling Custom Currencies, Master Key Weight seems not right.

### ISSUE THREAD

**Issue by farzbood** [stellar/new-docs#185]
### What version are you using?
Latest.

### What did you do?
Following the recommendations of this link. https://developers.stellar.org/docs/glossary/multisig/#example-5:-custom-currencies

### What did you expect to see?

I need to be able to validate "Trustlines" by signing an "Allow Trust" Operation.

### What did you see instead?
When/If you set the "Master Weight" (Master Key Weight: 0) you can't do it anymore.

P.S.
I believe that setting the "Master Weight" to a minimum (e.g. 1) and  "Medium and High thresholds" to a higher (e.g. 2) would be the correct practice.
Just suggest this to improve the Docs. if it seems right to you too.
Stay Safe.

**Comment by rice2000** [comment]
Thanks for this!  We ended up taking another look, and decided that we don't want to demonstrate this method of account locking since it's no longer best practice.

See:
https://github.com/stellar/new-docs/pull/259
