### ISSUE TITLE
Favicon missing on API Ref subpages

### ISSUE THREAD

**Issue by kylemccollom** [stellar/new-docs#195]
When you navigate to the API Ref's home page from the regular Docs, a favicon is present. But when you navigate deeper into the API Ref, the favicon disappears. You have to go back to the regular Docs, then revisit the API Ref to get the favicon back, and it disappears again if you navigate to a deeper API Ref page. On Chrome v83.0.4103.116 on macOS v10.15.4.

<img width="502" alt="Screen Shot 2020-07-20 at 10 45 38 AM" src="https://user-images.githubusercontent.com/22641985/87951129-30afca00-ca76-11ea-90a5-357dd83b67ef.png">

**Comment by shanzzam** [comment]
This is still an issue so am adding it to the Nebula team backlog as it's a technical issue.
