### ISSUE TITLE
Error on the 'Create Passive Sell Offer' Docs

### ISSUE THREAD

**Issue by L-Zuluaga** [stellar/new-docs#197]
## Problem
The documentation show the Offer ID field as one of the fields of the operation but stellar doesn't accept the operation containing that field, it gives a malformed transaction error when using this field on the operation.
https://developers.stellar.org/docs/start/list-of-operations/#create-passive-sell-offer
##
![image](https://user-images.githubusercontent.com/32212593/87976171-47641a00-ca92-11ea-98aa-68ecf03ce0e7.png)

#### Even Stellar Laboratory doesn't show the param when creating the operation:
![image](https://user-images.githubusercontent.com/32212593/87976372-9f9b1c00-ca92-11ea-8ed9-86fa8c5ab7e2.png)

**Comment by vcarl** [comment]
I scoped out [the XDR types](https://github.com/stellar/js-stellar-base/tree/0fbd0ad462e88448c20da5ef37622bf42840e26b/xdr/Stellar-transaction.x#L170-L176) for this to confirm, appears you're correct that `offer_id` shouldn't be listed here. Thanks for reporting @L-Zuluaga!
