### ISSUE TITLE
"fee_paid" no longer exist in Transaction Object Response Dict.

### ISSUE THREAD

**Issue by farzbood** [stellar/new-docs#199]
Based on my latest exprience, the `"fee_paid"` entry no longer exist in `Transaction Object` mentioned in documentation.
https://developers.stellar.org/api/resources/transactions/object/
It replaced by `"fee_account"` entry, which is fine by me though.
This is for sake of Documentaion Improvement.

**Comment by vcarl** [comment]
@rice2000 looks like `fee_charged` might be the updated entry? https://horizon.stellar.org/transactions?order=desc

**Comment by farzbood** [comment]
That's what it looks like in practice, I'm not sure if it's so by design though.
