### ISSUE TITLE
egress port listed as 11265 when it should be 11625

### ISSUE THREAD

**Issue by arduent** [stellar/new-docs#211]
Outbound: a Stellar Core needs to connect to other nodes via thier PEER_PORTs TCP. You can find information about other nodes’ PEER_PORTs on a network explorer like Stellarbeat, but most use the default port, which is, again, 11265.

if "again" means referencing the preceding sentence, the port is 11625

under heading "Network access" on https://developers.stellar.org/docs/run-core-node/prerequisites/

**Comment by rice2000** [comment]
Thanks for pointing this out!  Good eye.

Fixed: https://github.com/stellar/new-docs/pull/214
