### ISSUE TITLE
The new accounts/payments page doesn't load properly when scrolling

### ISSUE THREAD

**Issue by howardtw** [stellar/new-docs#221]
### What version are you using?

N/A

### What did you do?

When I tried to browse the account payments [page](https://developers.stellar.org/api/resources/accounts/payments/), it jumped to introduction [page](https://developers.stellar.org/api/introduction/) immediately after I scrolled down. It happened on both Chrome and Safari.

### What did you expect to see?

Page remains the same for scrolling.

### What did you see instead?

Browser took me to a different page.

**Comment by shanzzam** [comment]
@howardtw are you still seeing this behavior? I can't reproduce it now.

**Comment by vcarl** [comment]
Oops, I believe this was fixed in #223

**Comment by howardtw** [comment]
@shanzzam can't reproduce it either. I believe it's been fixed by #223 as @vcarl mentioned. Closing.
