### ISSUE TITLE
The Example Stellar-Wallet walk through does not produce a working app, and doesn't match the online example or the github source.

### ISSUE THREAD

**Issue by pperrin** [stellar/new-docs#226]
### What version are you using?
Last updated Aug. 26, 2020

### What did you do?
Followed the 'create an app' walk through on a windows 10 pc.

### What did you expect to see?
A locally running example stellar wallet (app).

### What did you see instead?
It failed to run at all.

The first issue was the app requiring HTTPS on local host. But having fixed this it was clear that the code in the walkthrough in the docs was broken and didn't even match the version of the code on github.

Having installed the github version and enabled HTTPS I had a functioning app, but it does not match the example online at https://stellar-demo-wallet.now.sh/ 

--

I am interested in learning to program for Stellar - the above issues are quite a barrier to getting started!

**Comment by rice2000** [comment]
@tyvdh When you get a chance, can you take a look at this?

**Comment by tyvdh** [comment]
Hey @pperrin, sorry for the issues. The `master` branch of the demo wallet is quite a different product from the tutorials, however if you stick with the linked branches they should all reflect the tutorial code pretty closely and run successfully now. 

If not please reach back out in this thread and we'll have a look.

Thanks for filing this issue!
