### ISSUE TITLE
SEP-24 & SEP-31 Docs Refactor Discussion

### ISSUE THREAD

**Issue by JakeUrban** [stellar/new-docs#231]
This issue is for discussing high-level organizational changes to the new docs.

There are a few things I noticed right away when it comes to the organization:

- the [Where To Start](https://developers.stellar.org/docs/start/introduction/) section gives plenty of links for the Stellar basics, but it doesn't clearly direct users by use-case. We should should have something like, _Want to facilitate deposits and withdraws to/from stellar? Go here. B2B payments? Go here_, etc.
- there is a [tutorials](https://developers.stellar.org/docs/tutorials/create-account/) section, but there are also seems to be tutorial-style docs in the [building apps](https://developers.stellar.org/docs/building-apps/) section, which is more of a how-to-build-a-wallet tutorial. I would suggest removing the building apps section and placing the same content in Tutorials.
- We should clearly distinguish between SEP-24 and SEP-31. This is more of a future TODO since I'll be adding SEP-31 content

Small fixes:

- [listing assets link](https://developers.stellar.org/docs/issuing-assets/list-asset-on-dex/) fails with 404 from [this page](https://developers.stellar.org/docs/issuing-assets/).

**Comment by JakeUrban** [comment]
CC @rice2000 

Just my initial thoughts, I'll probably edit my opinions as I work with the docs.

**Comment by JakeUrban** [comment]
Also can I be added as a contributor to the project so I assign this issue?

**Comment by rice2000** [comment]
Good suggestions! 

I think it makes sense to add SEP-31 content first, then update "Where to Start."  The building apps section requires a bit more thought, so I'd save that for last.  I think we want something separate from tutorials to help people understand the client side of things, and while you're probably right that it makes sense to move the current "How to Build a Wallet" content into "Tutorials," I think we may want to replace it with new content that guides app builders in a general way when we do.  

Also: I just filed a PR to add you as a contributor.

**Comment by JakeUrban** [comment]
I'm not sure what you mean regarding the Tutorials / Building Apps sections but I can just get started on the SEP-24/SEP-31 stuff and the "Where to Start" section for now.

**Comment by JakeUrban** [comment]
Closing because we're working on a refactor already
