### ISSUE TITLE
Deprecated reference to `horizon db backfill NUM_LEDGERS` in new docs

### ISSUE THREAD

**Issue by marcinx** [stellar/new-docs#235]
https://developers.stellar.org/docs/run-api-server/running/#ingesting-historical-data references `horizon db backfill NUM_LEDGERS` which does not exist in Horizon anymore (there is no backfill command). I guess it should mention `horizon db reingest range start end` instead. 

Additionally https://developers.stellar.org/docs/run-api-server/running/#ingesting-historical-data mentions `horizon db range [START_LEDGER] [END_LEDGER]` which should be `horizon db reingest range [START_LEDGER] [END_LEDGER]`

**Comment by rice2000** [comment]
Thanks!  And sorry for the delay.  I believe this is fixed by https://github.com/stellar/new-docs/pull/262
