### ISSUE TITLE
Channels Appears Twice in Glossary

### ISSUE THREAD

**Issue by jonjove** [stellar/new-docs#245]
### What did you do?
Clicked "Glossary"

### What did you expect to see?
Glossary in alphabetical order with no repeats.

### What did you see instead?
"Channels" appears between "Assets" and "Decentralized Exchange" as expected, and links to https://developers.stellar.org/docs/glossary/channels/. "Channels" also appears between "Operations" and "Stellar Consensus Protocol", and links to https://developers.stellar.org/docs/glossary/payment-channels/. These two pages are quite similar but not identical.

**Comment by rice2000** [comment]
Thanks @jonjove 

Solved by https://github.com/stellar/new-docs/pull/246.
