### ISSUE TITLE
Rendering Issue in Glossary for Claimable Balance

### ISSUE THREAD

**Issue by jonjove** [stellar/new-docs#253]
### What did you do?
I went to https://developers.stellar.org/docs/glossary/claimable-balance/.

### What did you expect to see?
Properly rendered headings, for example
```
Relevant operations
CreateClaimableBalance
Parameters
```

### What did you see instead?
```
Relevant operationsCreate Claimable BalanceParameters
```
Other headings have the same issue.

**Comment by jonjove** [comment]
https://developers.stellar.org/docs/glossary/sponsored-reserves/ is impacted as well.

**Comment by quietbits** [comment]
Related to: https://github.com/stellar/new-docs/issues/234

**Comment by Ogungodspower5** [comment]
Contact me
