### ISSUE TITLE
Glossary Still Seems out of Order

### ISSUE THREAD

**Issue by jonjove** [stellar/new-docs#256]
Related to #245.

### What did you do?
Opened the "Glossary" menu.

### What did you expect to see?
Glossary pages in alphabetical order.

### What did you see instead?
Glossary pages not in alphabetical order:
```
...
Operations
Channels
Stellar Consensus Protocol
...
```

I think the problem is that the "Channels" page actually links to https://developers.stellar.org/docs/glossary/payment-channels/ so it's getting sorted as "P". But payment channels it not a good name for that page anyway, since payment channels refers to technology for off-chain updating of state.

**Comment by rice2000** [comment]
Thanks for pointing this out!  Should be fixed by https://github.com/stellar/new-docs/pull/261
