### ISSUE TITLE
Doc Request: A larger variety of sponsored reserve use-case examples.

### ISSUE THREAD

**Issue by Shaptic** [stellar/new-docs#258]
### What problem does your feature solve?
Per [this comment](https://github.com/stellar/new-docs/pull/254#pullrequestreview-508800266), it'd be useful to have an SDK example describing more use cases of sponsored reserves.

### What would you like to see?
At minimum, 
 - An example in which a `EndSponsoringFutureReserves` operation has a `SourceAccount` field set to something non-default (that is, to someone other than the transaction submitter).
 - (to be expanded as needed)

### What alternatives are there?
n/a

**Comment by junnel19** [comment]
Hii
