### ISSUE TITLE
Links on the assets page redirect you to the wrong page

### ISSUE THREAD

**Issue by howardtw** [stellar/new-docs#276]
### What version are you using?

N/A

### What did you do?

On the [assets](https://developers.stellar.org/api/resources/assets/) page, when you click the 🔗 icon in front of the `The Asset Object` or `List All Assets`, both of them will redirect you to the [instruction](https://developers.stellar.org/api/introduction/) page.

### What did you expect to see?

Get a link to the title I click and stay on the same page so that I can copy the link.

### What did you see instead?

 🔗 icon in front of the `The Asset Object` and `List All Assets` redirected me to the [instruction](https://developers.stellar.org/api/introduction/) page.

**Comment by rice2000** [comment]
Hmm.  Yeah.  That's pretty funky.  @vcarl @jeesunikim who should look at this kind of thing at this point?

**Comment by vcarl** [comment]
The Nebula team is keeping an eye on the issues, Shannon/Iveta will prioritize

**Comment by vcarl** [comment]
Hm yeah this is a weird one though, and pretty high-profile. I'll try and find some spare some bandwidth to at least investigate
