### ISSUE TITLE
The description in "Control access to an asset" is incorrect

### ISSUE THREAD

**Issue by howardtw** [stellar/new-docs#277]
### What version are you using?

N/A

### What did you do?

N/A

### What did you expect to see?

In the Authorization Required [section](https://developers.stellar.org/docs/issuing-assets/control-asset-access/#authorization-required), this paragraph should be
```
There are two levels of authorization an asset issuer can grant using the allow_trust operation:
```
or
```
There are two levels of authorization an asset holder can be granted by the asset issuer using the allow_trust operation:
```
if I understand it correctly.

### What did you see instead?
```
There are two levels of authorization an asset holder can grant using the allow_trust operation:
```

**Comment by rice2000** [comment]
Fixed by https://github.com/stellar/new-docs/pull/278
