### ISSUE TITLE
Typo on Anchor Assets- Overview page 

### ISSUE THREAD

**Issue by ankebaas** [stellar/new-docs#279]
### What version are you using?
The latest.

### What did you do?
I opened the developer docs, then clicked on Anchor Assets, then Overview.

### What did you expect to see?
Cross-border payments spelled correctly.

### What did you see instead?

Cross-boder payments

**Comment by zech564** [comment]
What's this?

**Comment by ankebaas** [comment]
Fixed by https://github.com/stellar/new-docs/pull/281
