### ISSUE TITLE
Feature Request: Add Stellar Smart Contract documentation

### ISSUE THREAD

**Issue by rice2000** [stellar/new-docs#284]
We didn't port over the old Smart Contracts page:
https://github.com/stellar/docs/blob/master/guides/walkthroughs/stellar-smart-contracts.md

It's pretty out of date at this point, and a lot of new work is underway to rethink smart contract capabilities.  We should figure out whether to bring it over anyway — and if so, how much time to spend revising it — or whether to retire it pending a new doc covering similar topics.

**Comment by rice2000** [comment]
If the plan is to port it over, see https://github.com/stellar/docs/issues/547 for an issue that needs attention.

**Comment by Shaptic** [comment]
Closing in lieu of #363.
