### ISSUE TITLE
account memo required

### ISSUE THREAD

**Issue by lijianl** [stellar/new-docs#324]
### What version are you using?

"stellar-sdk": "^7.0.0"

### What did you do?

use sdk as a wallet  for a dex exchange

### What did you expect to see?

is there any account options to set which allow the account only accept payment transaction with memo

**Comment by rice2000** [comment]
There is a way to do this.  For details, see: https://www.stellar.org/developers-blog/fixing-memo-less-payments?locale=en

Basic idea: use a data entry to set `config.memo_required` to `1`

**Comment by ire-and-curses** [comment]
@lijianl You already raised this here: https://github.com/stellar/js-stellar-sdk/issues/611. Please don't keep asking the same question in different repos.
