### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by abu7860** [stellar/new-docs#331]
Operation 143707883442532353 - Payment
GAVE…BVRX transferred 79.59984 XLM to [Binance] GAHK…DB4A

Not received My binance account

**Comment by rice2000** [comment]
This is a repository containing the open-source Stellar documentation.  

If you are having an issue with a payment to or from Binance, you will need to contact their customer support: https://www.binance.com/en/support

For more info, see [this blog post](https://medium.com/stellar-community/help-i-forgot-my-stellar-memo-d62b3cc9c2f7#:~:text=I%20suggest%20finding%20your%20transaction,help%20you%20identify%20your%20transaction.).
