### ISSUE TITLE
Feature Request: Specify that claimable absolute time predicate must be seconds

### ISSUE THREAD

**Issue by agenio** [stellar/new-docs#345]
### What problem does your feature solve?
Avoid misunderstanding between a time expressed in milliseconds and seconds.

### What would you like to see?
Would be a good idea to specify that the absolute time predicate (claimable balance op.) is expressed in seconds,
at the moment is indicated as "generic" Unix Epoch.

**Comment by Shaptic** [comment]
I believe this is already the case in most places, but I agree that it could be improved.

In the [API reference for the object](https://developers.stellar.org/api/resources/claimablebalances/object/), we see seconds specified:

> `relBefore` string _(optional)_  
> A relative deadline for when the claimable balance can be claimed. The value represents the number of seconds since the close time of the ledger which created the claimable balance.

In the examples on the [glossary page](https://developers.stellar.org/docs/glossary/claimable-balance/#example), we see conversion to seconds:

```js
  // Create a claimable balance with our two above-described conditions.
  let soon = Math.ceil((Date.now() / 1000) + 60); // .now() is in ms
  let bCanClaim = sdk.Claimant.predicateBeforeRelativeTime("60");
  let aCanReclaim = sdk.Claimant.predicateNot(
    sdk.Claimant.predicateBeforeAbsoluteTime(soon.toString())
  );
```

However, the absolute predicates do in fact reference a generic "Unix epoch". I've opened #346 and stellar/js-stellar-base#389 to clarify this in the docs and API reference, respectively.
