### ISSUE TITLE
Change wording in "GitHub Issues" call for action on top of each page.

### ISSUE THREAD

**Issue by marcinx** [stellar/new-docs#356]
Currently the Docs display this on top of each page:

"These new docs are in beta. Please submit bugs to GitHub issues."

This sounds like the preferred way to report bugs/problems in the docs is to open an issue here. @rice2000 pointed out that since these docs are open source it might as well be a PR to minimize overhead. People can just fix things themselves then and submit for approval.

In light of that we could probably change the wording to something like "These docs are in beta. Please open a PR or create an issue on GitHub if you find a bug or typos."

PS: I'd open a PR for that but: "Brilliant question, and a funny one...because we should change the text at the top of the page to suggest that people open PRs, but that copy is actually part of a wrapper around the Github pages, so ironically, you'll need to open an issue to suggest that we ask people to file PRs." (Justin)

**Comment by shanzzam** [comment]
This has been changed to "Please submit any typos you come across to GitHub issues."
