### ISSUE TITLE
Inconsistencies on Run a Core Node -> Overview - Watcher missing?

### ISSUE THREAD

**Issue by wanecek** [stellar/new-docs#376]
On the [Overview](https://developers.stellar.org/docs/run-core-node/)-page of Run a Core Node, the docs describe the different types of nodes that one can configure using stellar core.

There are however some inconsistencies between the total number of node types that the text refers to, and I am wondering if maybe the Watcher type is missing? 

### [Types of nodes](https://developers.stellar.org/docs/run-core-node/#types-of-nodes)

Under the section "Types of nodes", the following can be read (emphasis mine):

> To make things easier, we’ll define **four** types of nodes based on permutations of those two options: Basic Validator, Full Validator, and Archiver. You’ll notice that they all support Horizon and submit transactions to the network:

This is followed by a table listing **three** node types. Similarly, further down on the same page, under the subsection "Archiver", the final sentence reads:

> Otherwise, you’re probably better off choosing one of the other **three** types.

While only two other node types are discussed.

---

I'm quite new to the Stellar network, and am unsure of if the three nodes listed are what's what, or if the Watcher node type (e.g. discussed in the Lumenauts videos and shown on on Stellarbeat.io) has been deprecated as a concept?

**Comment by wanecek** [comment]
Hmm, after finding reading the recent commit `[e8945ce2](https://github.com/stellar/new-docs/commit/e8945ce2cc245add925f6f74e0f816a05e75f488)` by @Shaptic, I believe it's only a matter of inconsistencies after editing the page to remove Watchers. I will submit a PR instead.

**Comment by Shaptic** [comment]
Thank you! Great catches and contributions, appreciated :pray: I think we should acknowledge Watchers' existence and explain that they're deprecated, as opposed to hide them as I did in #367.
