### ISSUE TITLE
Feature Request: Search bar on the docs page

### ISSUE THREAD

**Issue by nickgilbert** [stellar/new-docs#382]
### What problem does your feature solve? 
It would provide a way for a user of the docs site to search for content related to specific topics. 

### What would you like to see?
A search bar in the top nav which allowed you to search for information you were looking for. If we captured searches we could also understand what users were looking for and whether they were finding what they needed based on if the search was able to surface an answer to their query.

### What alternatives are there?
Today I use google to search the site by specifying the domain.

**Comment by Godspowerogun** [comment]
Cashapp payment 
Direct deposit to my cashapp 
Routing number: 041215663
Account number: 1313654799499
Any trading cash deposit to my cashapp

**Comment by shanzzam** [comment]
Will do some initial exploration of this to determine effort of implementation. Feature set includes search ability and analytics to help us improve the docs.
