### ISSUE TITLE
Money not correspond when I swap 

### ISSUE THREAD

**Issue by andry332** [stellar/new-docs#434]
### What version are you using?
LOBSTR 

### What did you do?
I try to swap spacestone but the price is not same like my wallet of LOBSTR 

### What did you expect to see?
18$

### What did you see instead?
Instead I see 0,84$

**Comment by shanzzam** [comment]
The developer documents aren't affiliated with Lobstr. I suggest looking at the support page https://lobstr.zendesk.com/hc/en-us/categories/360000002334-Help-Center/
