### ISSUE TITLE
Can't Sign XDR when trying to swap or do anything ...I transferred in from a different steller acct... 

### ISSUE THREAD

**Issue by PrettyPippy** [stellar/new-docs#437]
### What version are you using? I am not sure. Using a cell phone. 

 How do you do that on a phone? Newbie Here.

### What did you do? Try to swap xlm for anything or send back to original acct it came from... It always shows can't sign XDR... I created a lobster vault, thinking it would help... it says, can't sign XDR

 How do I enclose a picture? I am a newbie, and this sucks... trying to explain to someone... It's because a fucking hacker got in my other device. I created a new acct on a new device, tried to send my steller... and I did, but I can't swap it to yXLM because idk somehow the hacker follows me... It is like this with everything I do... Maybe it's not a hacker, but it's too coincidental, tell me what the hell I am doing wring! Please fix this!!

**Comment by rice2000** [comment]
Sorry to hear you are having issues!  This repo is for suggestions to improve the developer documentation, so it's limited to issues and pull requests that relate to technical information hosted on developers.stellar.org. It sounds like this is a request for tech support, which is outside the scope of this repo.

To get help, you should either:
* Contact customer support for the app or service you are using to access the Stellar network
* Reach out on community channels to get assistance from people building on and using the Stellar network such as the [Stellar Public Keybase](https://keybase.io/team/stellar.public), [Stellar Global](https://stellar-global.org/), or the [Stellar Stack Exchange](https://stellar.stackexchange.com/)
