### ISSUE TITLE
Cannot view docs on stellar.org

### ISSUE THREAD

**Issue by magick93** [stellar/new-docs#459]
### What version are you using?

I'm not building docs. Am trying to view them online.

### What did you do?

I tried to read docs on https://developers.stellar.org/docs/tutorials/create-account/

### What did you expect to see?

Some instructions on how to create an account.

### What did you see instead?

A blank page.

Opening the dev tools I see the following errors:

```

Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”. create-account:1:1
unreachable code after return statement
commons-2bb4081324bab558f9de.js:124
TypeError: n[(n.length - 1)] is undefined
    v performance.js:20
    V LayoutBase.js:48
    React 8
instrument.js:137:35
TypeError: n[(n.length - 1)] is undefined
    v performance.js:20
    V LayoutBase.js:48
    React 8
instrument.js:137:35
Uncaught TypeError: n[(n.length - 1)] is undefined
    v performance.js:20
    V LayoutBase.js:48
    React 8
performance.js:20:23
Uncaught TypeError: i.container is null
    highlightAllUnder prism.js:499
    s useHighlighting.js:7
    r helpers.js:87
prism.js:499:6
Uncaught TypeError: i.container is null
    highlightAllUnder prism.js:499
    s useHighlighting.js:7
    r helpers.js:87
prism.js:499:6
Uncaught TypeError: i.container is null
    highlightAllUnder prism.js:499
    s useHighlighting.js:7
    r helpers.js:87
prism.js:499:6

​

```

![image](https://user-images.githubusercontent.com/2173213/125388074-61c39180-e38e-11eb-979d-d11af0fadff8.png)

**Comment by ire-and-curses** [comment]
Are you still seeing this? I just tried the page and can't reproduce. Page loads and no errors on console. What browser/version/OS are you on?

**Comment by ire-and-curses** [comment]
Also: are you running any kind of JavaScript blocker?

**Comment by magick93** [comment]
I'm running Firefox 89.0.2 (64-bit) on Ubuntu 21.04 (Hirsute Hippo).

No Javascript blockers.

**Comment by magick93** [comment]
I did a git clone, then `yarn start` . Viewing locally I get a more pretty error:

![image](https://user-images.githubusercontent.com/2173213/125394104-afdd9280-e398-11eb-9846-2a54abb0e162.png)

**Comment by magick93** [comment]
This maybe the problem - https://bugzilla.mozilla.org/show_bug.cgi?id=1621729

**Comment by Shaptic** [comment]
I can confirm it breaks in Firefox + Arch if I set `resistFingerprinting: true` in my about:config, but it works fine without it.

**Comment by quietbits** [comment]
It's breaking for me on Windows in Firefox with `resistFingerprinting: true` as well, so it's not OS specific.
