### ISSUE TITLE
typo in the Welcome page first line

### ISSUE THREAD

**Issue by VikeshBaid** [stellar/new-docs#468]
**"This is the authoritative guide to all things Stellar"**
I think there is something **missing** in this line. I am new to stellar and trying to learn it via documents.
I have read this particular line thrice to understand that if am missing something in reading this line.

**Comment by Shaptic** [comment]
You can read it as "all things **related to** Stellar." This is an "old school" English phrase: https://english.stackexchange.com/q/252633/
