### ISSUE TITLE
Error in retrieving an offer:  https://horizon.stellar.org/offers/:offer_id

### ISSUE THREAD

**Issue by SunTeco** [stellar/new-docs#671]
### What version are you using?
##https://horizon.stellar.org/offers/:offer_id

{
  "type": "https://stellar.org/horizon-errors/not_found",
  "title": "Resource Missing",
  "status": 404,
  "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
}

**Comment by Shaptic** [comment]
It's possible that the offer was consumed and Stellar Expert doesn't reflect it yet, or the offer was so new that Horizon hadn't ingested it yet. Closing as this isn't a docs issue (if this is still a bug, you should file it with the SDK you're using). Regardless, what is the offer number?

**Comment by SunTeco** [comment]
Btw how can the consumed offer be retrieve in detail? 
Can you let me know the way to retrieve a consumed offer?
